## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
charity_df = application_df.drop(columns=['EIN', 'NAME'])
charity_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
charity_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
application_type_counts=charity_df['APPLICATION_TYPE'].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 500
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    charity_df['APPLICATION_TYPE'] = charity_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
charity_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
charity_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_counts = charity_df['CLASSIFICATION'].value_counts()
classification_counts_greater_than_1 = classification_counts[classification_counts > 1]
classification_counts_greater_than_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1800
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
charity_df = pd.get_dummies(charity_df)
charity_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = charity_df.drop(columns=['IS_SUCCESSFUL'])
y = charity_df['IS_SUCCESSFUL']

In [12]:
# Scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [13]:
from tensorflow.keras import regularizers

# Create a function to build the model with optimization techniques
def create_optimized_model():
    model = Sequential()

    # Input layer with L2 regularization and dropout for regularization
    model.add(Dense(64, input_dim=X_train.shape[1], activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.2))  # Dropout layer for regularization

    # Hidden layers with L2 regularization
    model.add(Dense(32, activation='relu', kernel_regularizer=l2(0.01)))
    model.add(Dropout(0.2))
    model.add(Dense(16, activation='relu', kernel_regularizer=l2(0.01)))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))  # Adjust if multi-class

    # Compile model with optimized settings
    optimizer = Adam(learning_rate=0.0005)  # Lower learning rate for stability
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [15]:
import h5py
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import load_model

In [17]:
from tensorflow.keras import regularizers

# Create a function to build the model with optimization techniques
def create_optimized_model():
    model = Sequential()

    # Input layer with L2 regularization and dropout for regularization
    model.add(Dense(64, input_dim=X_train.shape[1], activation='relu', kernel_regularizer=regularizers.l2(0.01)))
    model.add(Dropout(0.2))  # Dropout layer for regularization

    # Hidden layers with L2 regularization
    model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
    model.add(Dropout(0.2))
    model.add(Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.01)))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))  # Adjust if multi-class

    # Compile model with optimized settings
    optimizer = Adam(learning_rate=0.05)  # Lower learning rate for stability
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [20]:
# Define callbacks for early stopping and learning rate reduction
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6)
callbacks = [early_stopping, reduce_lr]

# Initialize and train the model
model = create_optimized_model()
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6513 - loss: 0.8228 - val_accuracy: 0.6994 - val_loss: 0.6920 - learning_rate: 0.0500
Epoch 2/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6690 - loss: 0.7217 - val_accuracy: 0.7019 - val_loss: 0.6711 - learning_rate: 0.0500
Epoch 3/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6718 - loss: 0.7278 - val_accuracy: 0.6472 - val_loss: 0.6836 - learning_rate: 0.0500
Epoch 4/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6578 - loss: 0.7127 - val_accuracy: 0.7131 - val_loss: 0.6756 - learning_rate: 0.0500
Epoch 5/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6589 - loss: 0.7155 - val_accuracy: 0.6975 - val_loss: 0.6782 - learning_rate: 0.0500
Epoch 6/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6920 - loss: 0.6662 - val_accuracy: 0.7128 - val_loss: 0.6647 - learning_rate: 0.0250
Epoch 7/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6921 - loss: 0.6647 - val_accuracy: 0.7137 - val_loss: 0.6293 - learning_rate: 0.0250
Epoch 8/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6804 - loss: 0.6754 - val_accuracy: 0.7114 - val_loss: 0.6691 - learning_rate: 0.0250
Epoch 9/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6930 - loss: 0.6625 - val_accuracy: 0.7121 - val_loss: 0.6666 - learning_rate: 0.0250
Epoch 10/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6846 - loss: 0.6736 - val_accuracy: 0.7098 - val_loss: 0.6459 - learning_rate: 0.0250
Epoch 11/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6945 - loss: 0.6470 - val_accuracy: 0.7128 - val_loss: 0.6308 - learning_rate: 0.0125
Epoch 12/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7014 - loss: 0.6372 - val_accuracy: 0.7188 - val_loss: 0.6324 - learning_rate: 0.0125

In [21]:
from tensorflow.keras import regularizers
from tensorflow.keras.layers import BatchNormalization

# Define an optimized neural network model
def create_high_accuracy_model():
    model = Sequential()

    # Input layer with batch normalization, L2 regularization, and dropout
    model.add(Dense(128, input_dim=X_train.shape[1], activation='relu', kernel_regularizer=regularizers.l2(0.001)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))  # Dropout to reduce overfitting

    # Hidden layers with increased neurons and batch normalization
    model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    model.add(Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.3))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))  # Use 'softmax' if multi-class

    # Compile model with an optimized learning rate
    optimizer = Adam(learning_rate=0.0001)  # Reduced learning rate for improved stability
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [22]:
# Callbacks to prevent overfitting and adjust learning rate
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6)
callbacks = [early_stopping, reduce_lr]

# Initialize and train the optimized model
model = create_high_accuracy_model()
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,          # Allow more epochs for thorough training
    batch_size=64,       # Larger batch size for stability
    callbacks=callbacks,
    verbose=1
)

Epoch 1/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.5402 - loss: 1.0364 - val_accuracy: 0.6829 - val_loss: 0.8780 - learning_rate: 1.0000e-04
Epoch 2/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6099 - loss: 0.9226 - val_accuracy: 0.6943 - val_loss: 0.8356 - learning_rate: 1.0000e-04
Epoch 3/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6392 - loss: 0.8747 - val_accuracy: 0.6991 - val_loss: 0.8130 - learning_rate: 1.0000e-04
Epoch 4/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6623 - loss: 0.8468 - val_accuracy: 0.7034 - val_loss: 0.7976 - learning_rate: 1.0000e-04
Epoch 5/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6868 - loss: 0.8186 - val_accuracy: 0.7115 - val_loss: 0.7852 - learning_rate: 1.0000e-04
Epoch 6/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6883 - loss: 0.8052 - val_accuracy: 0.7140 - val_loss: 0.7744 - learning_rate: 1.0000e-04
Epoch 7/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6934 - loss: 0.7930 - val_accuracy: 0.7160 - val_loss: 0.7625 - learning_rate: 1.0000e-04
Epoch 8/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6939 - loss: 0.7886 - val_accuracy: 0.7144 - val_loss: 0.7554 - learning_rate: 1.0000e-04
Epoch 9/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7048 - loss: 0.7704 - val_accuracy: 0.7185 - val_loss: 0.7473 - learning_rate: 1.0000e-04
Epoch 10/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7091 - loss: 0.7638 - val_accuracy: 0.7200 - val_loss: 0.7401 - learning_rate: 1.0000e-04
Epoch 11/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7096 - loss: 0.7524 - val_accuracy: 0.7208 - val_loss: 0.7338 - learning_rate: 1.0000e-04
Epoch 12/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7087 - loss: 0.7486 - val_accuracy: 0.7211 - val_loss: 0.7267 - learning_rate: 1.0000e-04
Epoch 13/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7142 - loss: 0.7441 - val_accuracy: 0.7230 - val_loss: 0.7197 - learning_rate: 1.0000e-04
Epoch 14/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7164 - loss: 0.7326 - val_accuracy: 0.7233 - val_loss: 0.7130 - learning_rate: 1.0000e-04
Epoch 15/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7144 - loss: 0.7286 - val_accuracy: 0.7242 - val_loss: 0.7067 - learning_rate: 1.0000e-04
Epoch 16/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7189 - loss: 0.7203 - val_accuracy: 0.7268 - val_loss: 0.7009 - learning_rate: 1.0000e-04
Epoch 17/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7214 - loss: 0.7125 - val_accuracy: 0.7273 - val_loss: 0.6943 - learning_rate: 1.0000e-04
Epoch 18/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7196 - loss: 0.7022 - val_accuracy: 0.7254 - val_loss: 0.6883 - learning_rate: 1.0000e-04
Epoch 19/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7233 - loss: 0.7029 - val_accuracy: 0.7257 - val_loss: 0.6836 - learning_rate: 1.0000e-04
Epoch 20/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7263 - loss: 0.6918 - val_accuracy: 0.7254 - val_loss: 0.6784 - learning_rate: 1.0000e-04
Epoch 21/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7213 - loss: 0.6906 - val_accuracy: 0.7276 - val_loss: 0.6727 - learning_rate: 1.0000e-04
Epoch 22/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7321 - loss: 0.6738 - val_accuracy: 0.7243 - val_loss: 0.6684 - learning_rate: 1.0000e-04
Epoch 23/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7211 - loss: 0.6790 - val_accuracy: 0.7238 - val_loss: 0.6631 - learning_rate: 1.0000e-04
Epoch 24/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7256 - loss: 0.6698 - val_accuracy: 0.7277 - val_loss: 0.6587 - learning_rate: 1.0000e-04
Epoch 25/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7200 - loss: 0.6705 - val_accuracy: 0.7278 - val_loss: 0.6538 - learning_rate: 1.0000e-04
Epoch 26/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7267 - loss: 0.6614 - val_accuracy: 0.7268 - val_loss: 0.6498 - learning_rate: 1.0000e-04
Epoch 27/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7282 - loss: 0.6549 - val_accuracy: 0.7239 - val_loss: 0.6459 - learning_rate: 1.0000e-04
Epoch 28/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7256 - loss: 0.6560 - val_accuracy: 0.7241 - val_loss: 0.6418 - learning_rate: 1.0000e-04
Epoch 29/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7247 - loss: 0.6540 - val_accuracy: 0.7271 - val_loss: 0.6379 - learning_rate: 1.0000e-04
Epoch 30/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7251 - loss: 0.6466 - val_accuracy: 0.7276 - val_loss: 0.6349 - learning_rate: 1.0000e-04
Epoch 31/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7283 - loss: 0.6386 - val_accuracy: 0.7270 - val_loss: 0.6321 - learning_rate: 1.0000e-04
Epoch 32/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7248 - loss: 0.6385 - val_accuracy: 0.7271 - val_loss: 0.6276 - learning_rate: 1.0000e-04
Epoch 33/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7332 - loss: 0.6292 - val_accuracy: 0.7271 - val_loss: 0.6240 - learning_rate: 1.0000e-04
Epoch 34/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7294 - loss: 0.6292 - val_accuracy: 0.7271 - val_loss: 0.6219 - learning_rate: 1.0000e-04
Epoch 35/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7318 - loss: 0.6234 - val_accuracy: 0.7284 - val_loss: 0.6186 - learning_rate: 1.0000e-04
Epoch 36/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7326 - loss: 0.6224 - val_accuracy: 0.7276 - val_loss: 0.6161 - learning_rate: 1.0000e-04
Epoch 37/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7263 - loss: 0.6237 - val_accuracy: 0.7276 - val_loss: 0.6132 - learning_rate: 1.0000e-04
Epoch 38/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7271 - loss: 0.6226 - val_accuracy: 0.7283 - val_loss: 0.6109 - learning_rate: 1.0000e-04
Epoch 39/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7290 - loss: 0.6183 - val_accuracy: 0.7283 - val_loss: 0.6094 - learning_rate: 1.0000e-04
Epoch 40/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7349 - loss: 0.6100 - val_accuracy: 0.7292 - val_loss: 0.6071 - learning_rate: 1.0000e-04
Epoch 41/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7326 - loss: 0.6111 - val_accuracy: 0.7293 - val_loss: 0.6056 - learning_rate: 1.0000e-04
Epoch 42/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7259 - loss: 0.6132 - val_accuracy: 0.7292 - val_loss: 0.6028 - learning_rate: 1.0000e-04
Epoch 43/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7309 - loss: 0.6072 - val_accuracy: 0.7273 - val_loss: 0.6007 - learning_rate: 1.0000e-04
Epoch 44/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7332 - loss: 0.6028 - val_accuracy: 0.7262 - val_loss: 0.5988 - learning_rate: 1.0000e-04
Epoch 45/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7297 - loss: 0.6048 - val_accuracy: 0.7268 - val_loss: 0.5966 - learning_rate: 1.0000e-04
Epoch 46/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7289 - loss: 0.6043 - val_accuracy: 0.7300 - val_loss: 0.5962 - learning_rate: 1.0000e-04
Epoch 47/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7254 - loss: 0.6086 - val_accuracy: 0.7262 - val_loss: 0.5938 - learning_rate: 1.0000e-04
Epoch 48/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7279 - loss: 0.6006 - val_accuracy: 0.7265 - val_loss: 0.5924 - learning_rate: 1.0000e-04
Epoch 49/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7320 - loss: 0.5962 - val_accuracy: 0.7274 - val_loss: 0.5903 - learning_rate: 1.0000e-04
Epoch 50/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7287 - loss: 0.5959 - val_accuracy: 0.7271 - val_loss: 0.5882 - learning_rate: 1.0000e-04
Epoch 51/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7322 - loss: 0.5938 - val_accuracy: 0.7270 - val_loss: 0.5880 - learning_rate: 1.0000e-04
Epoch 52/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7318 - loss: 0.5900 - val_accuracy: 0.7296 - val_loss: 0.5868 - learning_rate: 1.0000e-04
Epoch 53/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7317 - loss: 0.5893 - val_accuracy: 0.7293 - val_loss: 0.5854 - learning_rate: 1.0000e-04
Epoch 54/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7309 - loss: 0.5913 - val_accuracy: 0.7267 - val_loss: 0.5842 - learning_rate: 1.0000e-04
Epoch 55/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7287 - loss: 0.5905 - val_accuracy: 0.7276 - val_loss: 0.5834 - learning_rate: 1.0000e-04
Epoch 56/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7336 - loss: 0.5886 - val_accuracy: 0.7286 - val_loss: 0.5821 - learning_rate: 1.0000e-04
Epoch 57/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7354 - loss: 0.5802 - val_accuracy: 0.7262 - val_loss: 0.5817 - learning_rate: 1.0000e-04
Epoch 58/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7312 - loss: 0.5836 - val_accuracy: 0.7292 - val_loss: 0.5802 - learning_rate: 1.0000e-04
Epoch 59/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7332 - loss: 0.5775 - val_accuracy: 0.7278 - val_loss: 0.5788 - learning_rate: 1.0000e-04
Epoch 60/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7319 - loss: 0.5855 - val_accuracy: 0.7289 - val_loss: 0.5777 - learning_rate: 1.0000e-04
Epoch 61/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7331 - loss: 0.5826 - val_accuracy: 0.7278 - val_loss: 0.5778 - learning_rate: 1.0000e-04
Epoch 62/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7341 - loss: 0.5785 - val_accuracy: 0.7280 - val_loss: 0.5765 - learning_rate: 1.0000e-04
Epoch 63/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7300 - loss: 0.5787 - val_accuracy: 0.7305 - val_loss: 0.5752 - learning_rate: 1.0000e-04
Epoch 64/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7294 - loss: 0.5752 - val_accuracy: 0.7271 - val_loss: 0.5745 - learning_rate: 1.0000e-04
Epoch 65/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7344 - loss: 0.5777 - val_accuracy: 0.7312 - val_loss: 0.5743 - learning_rate: 1.0000e-04
Epoch 66/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7276 - loss: 0.5811 - val_accuracy: 0.7313 - val_loss: 0.5731 - learning_rate: 1.0000e-04
Epoch 67/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7314 - loss: 0.5780 - val_accuracy: 0.7312 - val_loss: 0.5731 - learning_rate: 1.0000e-04
Epoch 68/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7310 - loss: 0.5741 - val_accuracy: 0.7297 - val_loss: 0.5723 - learning_rate: 1.0000e-04
Epoch 69/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7309 - loss: 0.5775 - val_accuracy: 0.7270 - val_loss: 0.5716 - learning_rate: 1.0000e-04
Epoch 70/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7378 - loss: 0.5708 - val_accuracy: 0.7265 - val_loss: 0.5717 - learning_rate: 1.0000e-04
Epoch 71/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7279 - loss: 0.5782 - val_accuracy: 0.7281 - val_loss: 0.5699 - learning_rate: 1.0000e-04
Epoch 72/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7342 - loss: 0.5714 - val_accuracy: 0.7310 - val_loss: 0.5698 - learning_rate: 1.0000e-04
Epoch 73/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7347 - loss: 0.5710 - val_accuracy: 0.7273 - val_loss: 0.5694 - learning_rate: 1.0000e-04
Epoch 74/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7360 - loss: 0.5677 - val_accuracy: 0.7281 - val_loss: 0.5687 - learning_rate: 1.0000e-04
Epoch 75/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7362 - loss: 0.5668 - val_accuracy: 0.7276 - val_loss: 0.5687 - learning_rate: 1.0000e-04
Epoch 76/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7360 - loss: 0.5686 - val_accuracy: 0.7265 - val_loss: 0.5674 - learning_rate: 1.0000e-04
Epoch 77/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7342 - loss: 0.5694 - val_accuracy: 0.7296 - val_loss: 0.5674 - learning_rate: 1.0000e-04
Epoch 78/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7394 - loss: 0.5643 - val_accuracy: 0.7271 - val_loss: 0.5678 - learning_rate: 1.0000e-04
Epoch 79/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7341 - loss: 0.5708 - val_accuracy: 0.7294 - val_loss: 0.5668 - learning_rate: 1.0000e-04
Epoch 80/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7336 - loss: 0.5680 - val_accuracy: 0.7300 - val_loss: 0.5660 - learning_rate: 1.0000e-04
Epoch 81/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7333 - loss: 0.5667 - val_accuracy: 0.7318 - val_loss: 0.5654 - learning_rate: 1.0000e-04
Epoch 82/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7284 - loss: 0.5724 - val_accuracy: 0.7276 - val_loss: 0.5650 - learning_rate: 1.0000e-04
Epoch 83/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7315 - loss: 0.5679 - val_accuracy: 0.7278 - val_loss: 0.5649 - learning_rate: 1.0000e-04
Epoch 84/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7324 - loss: 0.5672 - val_accuracy: 0.7310 - val_loss: 0.5646 - learning_rate: 1.0000e-04
Epoch 85/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7327 - loss: 0.5673 - val_accuracy: 0.7303 - val_loss: 0.5642 - learning_rate: 1.0000e-04
Epoch 86/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7332 - loss: 0.5646 - val_accuracy: 0.7277 - val_loss: 0.5640 - learning_rate: 1.0000e-04
Epoch 87/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7362 - loss: 0.5630 - val_accuracy: 0.7322 - val_loss: 0.5637 - learning_rate: 1.0000e-04
Epoch 88/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7363 - loss: 0.5637 - val_accuracy: 0.7297 - val_loss: 0.5634 - learning_rate: 1.0000e-04
Epoch 89/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7433 - loss: 0.5597 - val_accuracy: 0.7316 - val_loss: 0.5642 - learning_rate: 1.0000e-04
Epoch 90/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7363 - loss: 0.5597 - val_accuracy: 0.7327 - val_loss: 0.5630 - learning_rate: 1.0000e-04
Epoch 91/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7379 - loss: 0.5590 - val_accuracy: 0.7303 - val_loss: 0.5629 - learning_rate: 1.0000e-04
Epoch 92/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7294 - loss: 0.5676 - val_accuracy: 0.7316 - val_loss: 0.5630 - learning_rate: 1.0000e-04
Epoch 93/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7340 - loss: 0.5639 - val_accuracy: 0.7319 - val_loss: 0.5627 - learning_rate: 1.0000e-04
Epoch 94/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7352 - loss: 0.5580 - val_accuracy: 0.7318 - val_loss: 0.5623 - learning_rate: 1.0000e-04
Epoch 95/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7317 - loss: 0.5629 - val_accuracy: 0.7300 - val_loss: 0.5621 - learning_rate: 1.0000e-04
Epoch 96/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7334 - loss: 0.5617 - val_accuracy: 0.7310 - val_loss: 0.5617 - learning_rate: 1.0000e-04
Epoch 97/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7372 - loss: 0.5613 - val_accuracy: 0.7322 - val_loss: 0.5625 - learning_rate: 1.0000e-04
Epoch 98/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7327 - loss: 0.5635 - val_accuracy: 0.7313 - val_loss: 0.5627 - learning_rate: 1.0000e-04
Epoch 99/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7398 - loss: 0.5531 - val_accuracy: 0.7328 - val_loss: 0.5617 - learning_rate: 1.0000e-04
Epoch 100/100
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7341 - loss: 0.5620 - val_accuracy: 0.7318 - val_loss: 0.5619 - learning_rate: 1.0000e-04

In [23]:
from tensorflow.keras import regularizers
from tensorflow.keras.layers import BatchNormalization

# Define a deeper and more robust model
def create_advanced_model():
    model = Sequential()

    # Input layer with a higher neuron count, L2 regularization, and dropout
    model.add(Dense(256, input_dim=X_train.shape[1], activation='relu', kernel_regularizer=regularizers.l2(0.002)))
    model.add(BatchNormalization())
    model.add(Dropout(0.4))  # Higher dropout to prevent overfitting

    # Additional hidden layers with high neuron counts
    model.add(Dense(128, activation='relu', kernel_regularizer=regularizers.l2(0.002)))
    model.add(BatchNormalization())
    model.add(Dropout(0.4))

    model.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.002)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.002)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    # Final layer before output
    model.add(Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.002)))
    model.add(Dropout(0.3))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))  # Binary classification

    # Compile the model with a very low learning rate for stability
    optimizer = Adam(learning_rate=0.00005)
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [24]:
# Define updated callbacks for early stopping and learning rate reduction
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=7, min_lr=1e-7)
callbacks = [early_stopping, reduce_lr]

# Initialize and train the advanced model
model = create_advanced_model()
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=150,         # Increase epochs to allow for full convergence
    batch_size=128,     # Larger batch size for batch stability
    callbacks=callbacks,
    verbose=1
)

Epoch 1/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.5238 - loss: 1.7791 - val_accuracy: 0.6411 - val_loss: 1.5796 - learning_rate: 5.0000e-05
Epoch 2/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5516 - loss: 1.6863 - val_accuracy: 0.6554 - val_loss: 1.5259 - learning_rate: 5.0000e-05
Epoch 3/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5784 - loss: 1.6258 - val_accuracy: 0.6560 - val_loss: 1.4918 - learning_rate: 5.0000e-05
Epoch 4/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5991 - loss: 1.5648 - val_accuracy: 0.6681 - val_loss: 1.4623 - learning_rate: 5.0000e-05
Epoch 5/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6121 - loss: 1.5317 - val_accuracy: 0.6682 - val_loss: 1.4386 - learning_rate: 5.0000e-05
Epoch 6/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6239 - loss: 1.4973 - val_accuracy: 0.6692 - val_loss: 1.4182 - learning_rate: 5.0000e-05
Epoch 7/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.6300 - loss: 1.4716 - val_accuracy: 0.6840 - val_loss: 1.3956 - learning_rate: 5.0000e-05
Epoch 8/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6407 - loss: 1.4453 - val_accuracy: 0.6876 - val_loss: 1.3759 - learning_rate: 5.0000e-05
Epoch 9/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6504 - loss: 1.4146 - val_accuracy: 0.6923 - val_loss: 1.3588 - learning_rate: 5.0000e-05
Epoch 10/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.6523 - loss: 1.3987 - val_accuracy: 0.6980 - val_loss: 1.3424 - learning_rate: 5.0000e-05
Epoch 11/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6636 - loss: 1.3757 - val_accuracy: 0.7012 - val_loss: 1.3244 - learning_rate: 5.0000e-05
Epoch 12/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6665 - loss: 1.3536 - val_accuracy: 0.7023 - val_loss: 1.3089 - learning_rate: 5.0000e-05
Epoch 13/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6669 - loss: 1.3389 - val_accuracy: 0.7093 - val_loss: 1.2935 - learning_rate: 5.0000e-05
Epoch 14/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6754 - loss: 1.3164 - val_accuracy: 0.7063 - val_loss: 1.2796 - learning_rate: 5.0000e-05
Epoch 15/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6839 - loss: 1.3010 - val_accuracy: 0.7106 - val_loss: 1.2652 - learning_rate: 5.0000e-05
Epoch 16/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6847 - loss: 1.2935 - val_accuracy: 0.7130 - val_loss: 1.2514 - learning_rate: 5.0000e-05
Epoch 17/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.6872 - loss: 1.2688 - val_accuracy: 0.7136 - val_loss: 1.2363 - learning_rate: 5.0000e-05
Epoch 18/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.6914 - loss: 1.2604 - val_accuracy: 0.7130 - val_loss: 1.2231 - learning_rate: 5.0000e-05
Epoch 19/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6956 - loss: 1.2438 - val_accuracy: 0.7149 - val_loss: 1.2086 - learning_rate: 5.0000e-05
Epoch 20/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6906 - loss: 1.2337 - val_accuracy: 0.7147 - val_loss: 1.1953 - learning_rate: 5.0000e-05
Epoch 21/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6943 - loss: 1.2147 - val_accuracy: 0.7153 - val_loss: 1.1810 - learning_rate: 5.0000e-05
Epoch 22/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6998 - loss: 1.2008 - val_accuracy: 0.7185 - val_loss: 1.1672 - learning_rate: 5.0000e-05
Epoch 23/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.6944 - loss: 1.1887 - val_accuracy: 0.7175 - val_loss: 1.1544 - learning_rate: 5.0000e-05
Epoch 24/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.7031 - loss: 1.1694 - val_accuracy: 0.7190 - val_loss: 1.1415 - learning_rate: 5.0000e-05
Epoch 25/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7037 - loss: 1.1568 - val_accuracy: 0.7194 - val_loss: 1.1280 - learning_rate: 5.0000e-05
Epoch 26/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7025 - loss: 1.1483 - val_accuracy: 0.7198 - val_loss: 1.1152 - learning_rate: 5.0000e-05
Epoch 27/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7064 - loss: 1.1355 - val_accuracy: 0.7187 - val_loss: 1.1018 - learning_rate: 5.0000e-05
Epoch 28/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7026 - loss: 1.1221 - val_accuracy: 0.7192 - val_loss: 1.0895 - learning_rate: 5.0000e-05
Epoch 29/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.7101 - loss: 1.1003 - val_accuracy: 0.7208 - val_loss: 1.0761 - learning_rate: 5.0000e-05
Epoch 30/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7120 - loss: 1.0895 - val_accuracy: 0.7190 - val_loss: 1.0643 - learning_rate: 5.0000e-05
Epoch 31/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7097 - loss: 1.0763 - val_accuracy: 0.7213 - val_loss: 1.0516 - learning_rate: 5.0000e-05
Epoch 32/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7093 - loss: 1.0691 - val_accuracy: 0.7220 - val_loss: 1.0393 - learning_rate: 5.0000e-05
Epoch 33/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7125 - loss: 1.0570 - val_accuracy: 0.7226 - val_loss: 1.0275 - learning_rate: 5.0000e-05
Epoch 34/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7141 - loss: 1.0435 - val_accuracy: 0.7227 - val_loss: 1.0160 - learning_rate: 5.0000e-05
Epoch 35/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7177 - loss: 1.0298 - val_accuracy: 0.7229 - val_loss: 1.0046 - learning_rate: 5.0000e-05
Epoch 36/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7175 - loss: 1.0186 - val_accuracy: 0.7232 - val_loss: 0.9925 - learning_rate: 5.0000e-05
Epoch 37/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7138 - loss: 1.0077 - val_accuracy: 0.7238 - val_loss: 0.9816 - learning_rate: 5.0000e-05
Epoch 38/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7189 - loss: 0.9904 - val_accuracy: 0.7239 - val_loss: 0.9711 - learning_rate: 5.0000e-05
Epoch 39/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7181 - loss: 0.9883 - val_accuracy: 0.7248 - val_loss: 0.9593 - learning_rate: 5.0000e-05
Epoch 40/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7150 - loss: 0.9743 - val_accuracy: 0.7252 - val_loss: 0.9491 - learning_rate: 5.0000e-05
Epoch 41/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7169 - loss: 0.9607 - val_accuracy: 0.7241 - val_loss: 0.9394 - learning_rate: 5.0000e-05
Epoch 42/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7181 - loss: 0.9521 - val_accuracy: 0.7241 - val_loss: 0.9288 - learning_rate: 5.0000e-05
Epoch 43/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7228 - loss: 0.9358 - val_accuracy: 0.7254 - val_loss: 0.9184 - learning_rate: 5.0000e-05
Epoch 44/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7159 - loss: 0.9320 - val_accuracy: 0.7264 - val_loss: 0.9079 - learning_rate: 5.0000e-05
Epoch 45/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7225 - loss: 0.9212 - val_accuracy: 0.7239 - val_loss: 0.8990 - learning_rate: 5.0000e-05
Epoch 46/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7207 - loss: 0.9117 - val_accuracy: 0.7242 - val_loss: 0.8894 - learning_rate: 5.0000e-05
Epoch 47/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7238 - loss: 0.8978 - val_accuracy: 0.7229 - val_loss: 0.8803 - learning_rate: 5.0000e-05
Epoch 48/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7220 - loss: 0.8913 - val_accuracy: 0.7230 - val_loss: 0.8715 - learning_rate: 5.0000e-05
Epoch 49/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7192 - loss: 0.8785 - val_accuracy: 0.7236 - val_loss: 0.8631 - learning_rate: 5.0000e-05
Epoch 50/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7308 - loss: 0.8679 - val_accuracy: 0.7236 - val_loss: 0.8549 - learning_rate: 5.0000e-05
Epoch 51/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7291 - loss: 0.8566 - val_accuracy: 0.7236 - val_loss: 0.8465 - learning_rate: 5.0000e-05
Epoch 52/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7207 - loss: 0.8559 - val_accuracy: 0.7232 - val_loss: 0.8380 - learning_rate: 5.0000e-05
Epoch 53/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7267 - loss: 0.8410 - val_accuracy: 0.7236 - val_loss: 0.8304 - learning_rate: 5.0000e-05
Epoch 54/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7255 - loss: 0.8377 - val_accuracy: 0.7238 - val_loss: 0.8227 - learning_rate: 5.0000e-05
Epoch 55/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.7242 - loss: 0.8309 - val_accuracy: 0.7239 - val_loss: 0.8150 - learning_rate: 5.0000e-05
Epoch 56/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.7294 - loss: 0.8187 - val_accuracy: 0.7248 - val_loss: 0.8075 - learning_rate: 5.0000e-05
Epoch 57/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7234 - loss: 0.8148 - val_accuracy: 0.7246 - val_loss: 0.8003 - learning_rate: 5.0000e-05
Epoch 58/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7219 - loss: 0.8111 - val_accuracy: 0.7241 - val_loss: 0.7934 - learning_rate: 5.0000e-05
Epoch 59/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7280 - loss: 0.7990 - val_accuracy: 0.7246 - val_loss: 0.7866 - learning_rate: 5.0000e-05
Epoch 60/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7273 - loss: 0.7922 - val_accuracy: 0.7249 - val_loss: 0.7799 - learning_rate: 5.0000e-05
Epoch 61/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7299 - loss: 0.7834 - val_accuracy: 0.7246 - val_loss: 0.7735 - learning_rate: 5.0000e-05
Epoch 62/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7262 - loss: 0.7781 - val_accuracy: 0.7246 - val_loss: 0.7677 - learning_rate: 5.0000e-05
Epoch 63/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7281 - loss: 0.7723 - val_accuracy: 0.7241 - val_loss: 0.7617 - learning_rate: 5.0000e-05
Epoch 64/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7224 - loss: 0.7697 - val_accuracy: 0.7241 - val_loss: 0.7560 - learning_rate: 5.0000e-05
Epoch 65/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7283 - loss: 0.7609 - val_accuracy: 0.7222 - val_loss: 0.7506 - learning_rate: 5.0000e-05
Epoch 66/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7303 - loss: 0.7515 - val_accuracy: 0.7227 - val_loss: 0.7450 - learning_rate: 5.0000e-05
Epoch 67/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7234 - loss: 0.7527 - val_accuracy: 0.7238 - val_loss: 0.7396 - learning_rate: 5.0000e-05
Epoch 68/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7272 - loss: 0.7465 - val_accuracy: 0.7236 - val_loss: 0.7338 - learning_rate: 5.0000e-05
Epoch 69/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7286 - loss: 0.7402 - val_accuracy: 0.7227 - val_loss: 0.7294 - learning_rate: 5.0000e-05
Epoch 70/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7236 - loss: 0.7395 - val_accuracy: 0.7236 - val_loss: 0.7245 - learning_rate: 5.0000e-05
Epoch 71/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7308 - loss: 0.7282 - val_accuracy: 0.7238 - val_loss: 0.7199 - learning_rate: 5.0000e-05
Epoch 72/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7264 - loss: 0.7235 - val_accuracy: 0.7229 - val_loss: 0.7147 - learning_rate: 5.0000e-05
Epoch 73/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7245 - loss: 0.7203 - val_accuracy: 0.7230 - val_loss: 0.7108 - learning_rate: 5.0000e-05
Epoch 74/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7249 - loss: 0.7184 - val_accuracy: 0.7226 - val_loss: 0.7067 - learning_rate: 5.0000e-05
Epoch 75/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7276 - loss: 0.7118 - val_accuracy: 0.7239 - val_loss: 0.7019 - learning_rate: 5.0000e-05
Epoch 76/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7272 - loss: 0.7077 - val_accuracy: 0.7239 - val_loss: 0.6977 - learning_rate: 5.0000e-05
Epoch 77/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7263 - loss: 0.7056 - val_accuracy: 0.7242 - val_loss: 0.6939 - learning_rate: 5.0000e-05
Epoch 78/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7270 - loss: 0.6979 - val_accuracy: 0.7245 - val_loss: 0.6902 - learning_rate: 5.0000e-05
Epoch 79/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7273 - loss: 0.6935 - val_accuracy: 0.7248 - val_loss: 0.6862 - learning_rate: 5.0000e-05
Epoch 80/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7294 - loss: 0.6918 - val_accuracy: 0.7246 - val_loss: 0.6828 - learning_rate: 5.0000e-05
Epoch 81/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7247 - loss: 0.6866 - val_accuracy: 0.7243 - val_loss: 0.6790 - learning_rate: 5.0000e-05
Epoch 82/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7295 - loss: 0.6822 - val_accuracy: 0.7241 - val_loss: 0.6753 - learning_rate: 5.0000e-05
Epoch 83/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7266 - loss: 0.6831 - val_accuracy: 0.7232 - val_loss: 0.6722 - learning_rate: 5.0000e-05
Epoch 84/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7323 - loss: 0.6755 - val_accuracy: 0.7259 - val_loss: 0.6694 - learning_rate: 5.0000e-05
Epoch 85/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7308 - loss: 0.6715 - val_accuracy: 0.7245 - val_loss: 0.6660 - learning_rate: 5.0000e-05
Epoch 86/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7301 - loss: 0.6717 - val_accuracy: 0.7246 - val_loss: 0.6629 - learning_rate: 5.0000e-05
Epoch 87/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7283 - loss: 0.6703 - val_accuracy: 0.7252 - val_loss: 0.6603 - learning_rate: 5.0000e-05
Epoch 88/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7303 - loss: 0.6660 - val_accuracy: 0.7258 - val_loss: 0.6569 - learning_rate: 5.0000e-05
Epoch 89/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.7304 - loss: 0.6575 - val_accuracy: 0.7261 - val_loss: 0.6544 - learning_rate: 5.0000e-05
Epoch 90/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.7304 - loss: 0.6573 - val_accuracy: 0.7246 - val_loss: 0.6521 - learning_rate: 5.0000e-05
Epoch 91/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7340 - loss: 0.6534 - val_accuracy: 0.7257 - val_loss: 0.6491 - learning_rate: 5.0000e-05
Epoch 92/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7324 - loss: 0.6525 - val_accuracy: 0.7245 - val_loss: 0.6467 - learning_rate: 5.0000e-05
Epoch 93/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7257 - loss: 0.6522 - val_accuracy: 0.7248 - val_loss: 0.6445 - learning_rate: 5.0000e-05
Epoch 94/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7303 - loss: 0.6492 - val_accuracy: 0.7249 - val_loss: 0.6417 - learning_rate: 5.0000e-05
Epoch 95/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.7322 - loss: 0.6437 - val_accuracy: 0.7249 - val_loss: 0.6394 - learning_rate: 5.0000e-05
Epoch 96/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.7309 - loss: 0.6457 - val_accuracy: 0.7242 - val_loss: 0.6376 - learning_rate: 5.0000e-05
Epoch 97/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7310 - loss: 0.6391 - val_accuracy: 0.7239 - val_loss: 0.6345 - learning_rate: 5.0000e-05
Epoch 98/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7302 - loss: 0.6438 - val_accuracy: 0.7251 - val_loss: 0.6325 - learning_rate: 5.0000e-05
Epoch 99/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7324 - loss: 0.6361 - val_accuracy: 0.7241 - val_loss: 0.6309 - learning_rate: 5.0000e-05
Epoch 100/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7337 - loss: 0.6297 - val_accuracy: 0.7261 - val_loss: 0.6288 - learning_rate: 5.0000e-05
Epoch 101/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7321 - loss: 0.6335 - val_accuracy: 0.7258 - val_loss: 0.6266 - learning_rate: 5.0000e-05
Epoch 102/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7276 - loss: 0.6364 - val_accuracy: 0.7258 - val_loss: 0.6247 - learning_rate: 5.0000e-05
Epoch 103/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7310 - loss: 0.6256 - val_accuracy: 0.7252 - val_loss: 0.6232 - learning_rate: 5.0000e-05
Epoch 104/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7313 - loss: 0.6255 - val_accuracy: 0.7249 - val_loss: 0.6215 - learning_rate: 5.0000e-05
Epoch 105/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7315 - loss: 0.6239 - val_accuracy: 0.7249 - val_loss: 0.6195 - learning_rate: 5.0000e-05
Epoch 106/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7311 - loss: 0.6235 - val_accuracy: 0.7249 - val_loss: 0.6182 - learning_rate: 5.0000e-05
Epoch 107/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7322 - loss: 0.6202 - val_accuracy: 0.7251 - val_loss: 0.6165 - learning_rate: 5.0000e-05
Epoch 108/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7289 - loss: 0.6243 - val_accuracy: 0.7257 - val_loss: 0.6150 - learning_rate: 5.0000e-05
Epoch 109/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7326 - loss: 0.6157 - val_accuracy: 0.7271 - val_loss: 0.6135 - learning_rate: 5.0000e-05
Epoch 110/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7320 - loss: 0.6160 - val_accuracy: 0.7274 - val_loss: 0.6128 - learning_rate: 5.0000e-05
Epoch 111/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7260 - loss: 0.6183 - val_accuracy: 0.7276 - val_loss: 0.6106 - learning_rate: 5.0000e-05
Epoch 112/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7300 - loss: 0.6192 - val_accuracy: 0.7277 - val_loss: 0.6093 - learning_rate: 5.0000e-05
Epoch 113/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7287 - loss: 0.6133 - val_accuracy: 0.7294 - val_loss: 0.6076 - learning_rate: 5.0000e-05
Epoch 114/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7376 - loss: 0.6062 - val_accuracy: 0.7286 - val_loss: 0.6065 - learning_rate: 5.0000e-05
Epoch 115/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7323 - loss: 0.6095 - val_accuracy: 0.7283 - val_loss: 0.6048 - learning_rate: 5.0000e-05
Epoch 116/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.7319 - loss: 0.6089 - val_accuracy: 0.7290 - val_loss: 0.6041 - learning_rate: 5.0000e-05
Epoch 117/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7337 - loss: 0.6058 - val_accuracy: 0.7287 - val_loss: 0.6032 - learning_rate: 5.0000e-05
Epoch 118/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7323 - loss: 0.6057 - val_accuracy: 0.7287 - val_loss: 0.6021 - learning_rate: 5.0000e-05
Epoch 119/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7378 - loss: 0.6032 - val_accuracy: 0.7249 - val_loss: 0.6011 - learning_rate: 5.0000e-05
Epoch 120/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7320 - loss: 0.6071 - val_accuracy: 0.7277 - val_loss: 0.6000 - learning_rate: 5.0000e-05
Epoch 121/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.7299 - loss: 0.6026 - val_accuracy: 0.7281 - val_loss: 0.5989 - learning_rate: 5.0000e-05
Epoch 122/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7336 - loss: 0.6041 - val_accuracy: 0.7280 - val_loss: 0.5981 - learning_rate: 5.0000e-05
Epoch 123/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7343 - loss: 0.5973 - val_accuracy: 0.7246 - val_loss: 0.5970 - learning_rate: 5.0000e-05
Epoch 124/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7348 - loss: 0.5986 - val_accuracy: 0.7283 - val_loss: 0.5959 - learning_rate: 5.0000e-05
Epoch 125/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.7307 - loss: 0.6015 - val_accuracy: 0.7278 - val_loss: 0.5954 - learning_rate: 5.0000e-05
Epoch 126/150
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7321 - loss: 0.5994 - val_accuracy: 0.7278 - val_loss: 0.5938 - learning_rate: 5.0000e-05
Epoch 127/150

In [28]:
# Saving the above model in h5 file.
model.save('AlphabetSoupCharity_Optimization.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [25]:
# Initialize the Sequential model
nn = Sequential()

# Input layer with first hidden layer
nn.add(Dense(units=128, activation="relu", input_dim=108))  # Increased units for more complex feature extraction
nn.add(BatchNormalization())  # Batch normalization for stable training
nn.add(Dropout(0.3))  # Dropout to prevent overfitting

# Second hidden layer
nn.add(Dense(units=64, activation="relu"))
nn.add(BatchNormalization())
nn.add(Dropout(0.3))

# Third hidden layer
nn.add(Dense(units=32, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(0.001)))
nn.add(BatchNormalization())
nn.add(Dropout(0.2))

# Fourth hidden layer
nn.add(Dense(units=16, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(0.001)))
nn.add(Dropout(0.2))

# Output layer
nn.add(Dense(units=1, activation="sigmoid"))

# Compile the model with an optimized learning rate
optimizer = Adam(learning_rate=0.00005)  # Fine-tuned learning rate for stable training
nn.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy"])

# Check the structure of the model
nn.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                     │ (None, 128)                 │          13,952 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_7                │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_11 (Dropout)                 │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_8                │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_12 (Dropout)                 │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_9                │ (None, 32)                  │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_13 (Dropout)                 │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_14 (Dropout)                 │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 25,729 (100.50 KB)

 Trainable params: 25,281 (98.75 KB)

 Non-trainable params: 448 (1.75 KB)

## Compile, Train and Evaluate the Model

In [27]:
# Define updated callbacks for early stopping and learning rate reduction
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=5, min_lr=1e-6)

# Train the model
history = nn.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=70,
    batch_size=64,
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

Epoch 1/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.5859 - loss: 0.8202 - val_accuracy: 0.6813 - val_loss: 0.6930 - learning_rate: 5.0000e-05
Epoch 2/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.6220 - loss: 0.7637 - val_accuracy: 0.7006 - val_loss: 0.6752 - learning_rate: 5.0000e-05
Epoch 3/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6402 - loss: 0.7401 - val_accuracy: 0.7080 - val_loss: 0.6644 - learning_rate: 5.0000e-05
Epoch 4/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6457 - loss: 0.7274 - val_accuracy: 0.7090 - val_loss: 0.6568 - learning_rate: 5.0000e-05
Epoch 5/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6587 - loss: 0.7116 - val_accuracy: 0.7144 - val_loss: 0.6526 - learning_rate: 5.0000e-05
Epoch 6/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.6675 - loss: 0.6974 - val_accuracy: 0.7155 - val_loss: 0.6497 - learning_rate: 5.0000e-05
Epoch 7/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6754 - loss: 0.6895 - val_accuracy: 0.7157 - val_loss: 0.6477 - learning_rate: 5.0000e-05
Epoch 8/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6762 - loss: 0.6888 - val_accuracy: 0.7185 - val_loss: 0.6428 - learning_rate: 5.0000e-05
Epoch 9/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6847 - loss: 0.6741 - val_accuracy: 0.7188 - val_loss: 0.6405 - learning_rate: 5.0000e-05
Epoch 10/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6858 - loss: 0.6795 - val_accuracy: 0.7185 - val_loss: 0.6406 - learning_rate: 5.0000e-05
Epoch 11/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6857 - loss: 0.6663 - val_accuracy: 0.7188 - val_loss: 0.6361 - learning_rate: 5.0000e-05
Epoch 12/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6901 - loss: 0.6639 - val_accuracy: 0.7181 - val_loss: 0.6347 - learning_rate: 5.0000e-05
Epoch 13/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6890 - loss: 0.6682 - val_accuracy: 0.7190 - val_loss: 0.6333 - learning_rate: 5.0000e-05
Epoch 14/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6976 - loss: 0.6622 - val_accuracy: 0.7194 - val_loss: 0.6318 - learning_rate: 5.0000e-05
Epoch 15/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7017 - loss: 0.6525 - val_accuracy: 0.7192 - val_loss: 0.6300 - learning_rate: 5.0000e-05
Epoch 16/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7008 - loss: 0.6473 - val_accuracy: 0.7200 - val_loss: 0.6294 - learning_rate: 5.0000e-05
Epoch 17/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7072 - loss: 0.6463 - val_accuracy: 0.7201 - val_loss: 0.6278 - learning_rate: 5.0000e-05
Epoch 18/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7015 - loss: 0.6520 - val_accuracy: 0.7210 - val_loss: 0.6260 - learning_rate: 5.0000e-05
Epoch 19/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7103 - loss: 0.6394 - val_accuracy: 0.7214 - val_loss: 0.6253 - learning_rate: 5.0000e-05
Epoch 20/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7081 - loss: 0.6419 - val_accuracy: 0.7216 - val_loss: 0.6235 - learning_rate: 5.0000e-05
Epoch 21/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7134 - loss: 0.6375 - val_accuracy: 0.7223 - val_loss: 0.6223 - learning_rate: 5.0000e-05
Epoch 22/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7088 - loss: 0.6375 - val_accuracy: 0.7214 - val_loss: 0.6216 - learning_rate: 5.0000e-05
Epoch 23/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7146 - loss: 0.6350 - val_accuracy: 0.7245 - val_loss: 0.6191 - learning_rate: 5.0000e-05
Epoch 24/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7172 - loss: 0.6289 - val_accuracy: 0.7222 - val_loss: 0.6189 - learning_rate: 5.0000e-05
Epoch 25/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7217 - loss: 0.6281 - val_accuracy: 0.7222 - val_loss: 0.6184 - learning_rate: 5.0000e-05
Epoch 26/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7178 - loss: 0.6256 - val_accuracy: 0.7223 - val_loss: 0.6168 - learning_rate: 5.0000e-05
Epoch 27/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7138 - loss: 0.6287 - val_accuracy: 0.7230 - val_loss: 0.6151 - learning_rate: 5.0000e-05
Epoch 28/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7177 - loss: 0.6234 - val_accuracy: 0.7232 - val_loss: 0.6142 - learning_rate: 5.0000e-05
Epoch 29/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7166 - loss: 0.6255 - val_accuracy: 0.7249 - val_loss: 0.6133 - learning_rate: 5.0000e-05
Epoch 30/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7187 - loss: 0.6240 - val_accuracy: 0.7255 - val_loss: 0.6121 - learning_rate: 5.0000e-05
Epoch 31/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7204 - loss: 0.6173 - val_accuracy: 0.7224 - val_loss: 0.6141 - learning_rate: 5.0000e-05
Epoch 32/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7163 - loss: 0.6205 - val_accuracy: 0.7222 - val_loss: 0.6119 - learning_rate: 5.0000e-05
Epoch 33/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7168 - loss: 0.6206 - val_accuracy: 0.7243 - val_loss: 0.6116 - learning_rate: 5.0000e-05
Epoch 34/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7147 - loss: 0.6248 - val_accuracy: 0.7257 - val_loss: 0.6103 - learning_rate: 5.0000e-05
Epoch 35/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7210 - loss: 0.6126 - val_accuracy: 0.7248 - val_loss: 0.6088 - learning_rate: 5.0000e-05
Epoch 36/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7220 - loss: 0.6155 - val_accuracy: 0.7264 - val_loss: 0.6097 - learning_rate: 5.0000e-05
Epoch 37/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7253 - loss: 0.6085 - val_accuracy: 0.7264 - val_loss: 0.6083 - learning_rate: 5.0000e-05
Epoch 38/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7218 - loss: 0.6139 - val_accuracy: 0.7261 - val_loss: 0.6067 - learning_rate: 5.0000e-05
Epoch 39/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7226 - loss: 0.6095 - val_accuracy: 0.7267 - val_loss: 0.6059 - learning_rate: 5.0000e-05
Epoch 40/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7233 - loss: 0.6085 - val_accuracy: 0.7281 - val_loss: 0.6047 - learning_rate: 5.0000e-05
Epoch 41/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7222 - loss: 0.6078 - val_accuracy: 0.7271 - val_loss: 0.6050 - learning_rate: 5.0000e-05
Epoch 42/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7261 - loss: 0.6045 - val_accuracy: 0.7262 - val_loss: 0.6040 - learning_rate: 5.0000e-05
Epoch 43/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7262 - loss: 0.6021 - val_accuracy: 0.7278 - val_loss: 0.6029 - learning_rate: 5.0000e-05
Epoch 44/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7203 - loss: 0.6105 - val_accuracy: 0.7276 - val_loss: 0.6015 - learning_rate: 5.0000e-05
Epoch 45/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7258 - loss: 0.6045 - val_accuracy: 0.7271 - val_loss: 0.6041 - learning_rate: 5.0000e-05
Epoch 46/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7209 - loss: 0.6070 - val_accuracy: 0.7271 - val_loss: 0.6011 - learning_rate: 5.0000e-05
Epoch 47/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7231 - loss: 0.6002 - val_accuracy: 0.7281 - val_loss: 0.6008 - learning_rate: 5.0000e-05
Epoch 48/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7276 - loss: 0.5991 - val_accuracy: 0.7278 - val_loss: 0.5995 - learning_rate: 5.0000e-05
Epoch 49/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7212 - loss: 0.6041 - val_accuracy: 0.7274 - val_loss: 0.5976 - learning_rate: 5.0000e-05
Epoch 50/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7280 - loss: 0.5971 - val_accuracy: 0.7278 - val_loss: 0.5983 - learning_rate: 5.0000e-05
Epoch 51/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7338 - loss: 0.5905 - val_accuracy: 0.7257 - val_loss: 0.5982 - learning_rate: 5.0000e-05
Epoch 52/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7288 - loss: 0.5973 - val_accuracy: 0.7273 - val_loss: 0.5972 - learning_rate: 5.0000e-05
Epoch 53/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7249 - loss: 0.5979 - val_accuracy: 0.7273 - val_loss: 0.5974 - learning_rate: 5.0000e-05
Epoch 54/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7286 - loss: 0.5936 - val_accuracy: 0.7257 - val_loss: 0.5959 - learning_rate: 5.0000e-05
Epoch 55/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7290 - loss: 0.5915 - val_accuracy: 0.7274 - val_loss: 0.5973 - learning_rate: 5.0000e-05
Epoch 56/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7307 - loss: 0.5979 - val_accuracy: 0.7257 - val_loss: 0.5953 - learning_rate: 5.0000e-05
Epoch 57/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7267 - loss: 0.5921 - val_accuracy: 0.7276 - val_loss: 0.5951 - learning_rate: 5.0000e-05
Epoch 58/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7251 - loss: 0.5955 - val_accuracy: 0.7268 - val_loss: 0.5933 - learning_rate: 5.0000e-05
Epoch 59/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7268 - loss: 0.5894 - val_accuracy: 0.7257 - val_loss: 0.5920 - learning_rate: 5.0000e-05
Epoch 60/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7234 - loss: 0.5988 - val_accuracy: 0.7257 - val_loss: 0.5922 - learning_rate: 5.0000e-05
Epoch 61/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7305 - loss: 0.5870 - val_accuracy: 0.7254 - val_loss: 0.5902 - learning_rate: 5.0000e-05
Epoch 62/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7242 - loss: 0.5913 - val_accuracy: 0.7257 - val_loss: 0.5912 - learning_rate: 5.0000e-05
Epoch 63/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7246 - loss: 0.5935 - val_accuracy: 0.7257 - val_loss: 0.5894 - learning_rate: 5.0000e-05
Epoch 64/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7310 - loss: 0.5869 - val_accuracy: 0.7280 - val_loss: 0.5899 - learning_rate: 5.0000e-05
Epoch 65/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7257 - loss: 0.5885 - val_accuracy: 0.7246 - val_loss: 0.5879 - learning_rate: 5.0000e-05
Epoch 66/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7245 - loss: 0.5885 - val_accuracy: 0.7258 - val_loss: 0.5881 - learning_rate: 5.0000e-05
Epoch 67/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7297 - loss: 0.5838 - val_accuracy: 0.7248 - val_loss: 0.5876 - learning_rate: 5.0000e-05
Epoch 68/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7318 - loss: 0.5815 - val_accuracy: 0.7245 - val_loss: 0.5867 - learning_rate: 5.0000e-05
Epoch 69/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7288 - loss: 0.5867 - val_accuracy: 0.7259 - val_loss: 0.5864 - learning_rate: 5.0000e-05
Epoch 70/70
429/429 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7299 - loss: 0.5828 - val_accuracy: 0.7280 - val_loss: 0.5871 - learning_rate: 5.0000e-05